src/binwalk/magic/firmware
I haven't been able to test most of these because I don't have the appropriate firmware image type, but I doubt that checksums, sizes, offsets, and addresses should ever be negative.
=> fix more signedness issues

deps.sh
modified the deps.sh to include updated yum commands as well as RedHat/CentOS specific package names.
=> Update deps.sh to support CentOS

INSTALL.md, src/binwalk/config/extract.conf, src/binwalk/magic/filesystems, src/binwalk/plugins/ubivalid.py
Issue https://github.com/devttys0/binwalk/issues/129
=> ubifs extraction

src/binwalk/magic/efi, src/binwalk/magic/firmware
After an interesting thread on Twitter with @theopolis and @LongSoft I ended up adding some more support for EFI structures identification.
=> Improve (U)EFI structures detection

src/binwalk/magic/firmware
just a few file formats used by Android firmware/bootloader developers
=> several firmware magics

src/binwalk/magic/firmware
Firmware update signatures for CSR Bluecore modules commonly found in Bluetooth audio devices.
=> CSR Bluecore DFU (firmware update) file format

src/binwalk/magic/animation, src/binwalk/magic/misc
Reference: http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/swf/pdf/swf-file-format-spec.pdf Chapter 2 "The SWF header"
Signed-off-by: Icenowy Zheng <icenowy@aosc.xyz>
=> Add Adobe Flash's SWF file (the uncompressed variant)

src/binwalk/magic/archives
This adds detection of XAR archive files.
Cf. https://en.wikipedia.org/wiki/Xar_(archiver) for details.
=> Include signatures for XAR archive format

src/binwalk/magic/firmware
Ref: [roman-yepishev/acer-tools/tree/master/msmptbl](https://github.com/roman-yepishev/acer-tools/tree/master/msmptbl).
Encountered during analysis of `UPDATA.APP` extracted from Huawei EC315 Firmware Update - 11.102.99.60.00 (Universal).
=> Added msm parition table signature

src/binwalk/magic/filesystems
MPFS (Microchip PIC File System)
=> Typo: Microchop --> Microchip

README.md
**Can be rejected**
_Added minor changes to README.md_
Changes include:
* Added TOC _containing links to most important parts of wiki (from the first toc in wiki index)_
* Added some badges
* Fixed Travis badge not always showing correct
* Top level titles to subtitles
* Added Quick start subheader on top of installation and usage
Updated README.md to be more informative
=> More Informative README.md

deps.sh
Add cramfs tools support for ubuntu 18.04.
=> fix issue #343

src/binwalk/core/magic.py, src/binwalk/magic/filesystems, src/binwalk/modules/disasm.py, src/binwalk/plugins/dlromfsextract.py, src/binwalk/plugins/unpfs.py
=> Changed endianess to endianness.

setup.py
Same thing you did with install and build, but for sdist.
=> Adding version into sdist

src/binwalk/magic/crypto
Detect PKCS#7 object signatures in signed firmware images.
=> Added PKCS#7 Object signature

deps.sh
Jefferson has moved to Python 3. This requires changes to `deps.sh`
=> Update deps.sh for Python 3 jefferson

src/binwalk/magic/linux
[Image.zip](https://github.com/ReFirmLabs/binwalk/files/4411073/Image.zip)
This commit adds a signature for ARM64 Linux images.
ARM64 Linux images have a special header described by https://www.kernel.org/doc/Documentation/arm64/booting.txt.
Output without the commit applied:
```
[tsys@sunsetshimmer binwalk]$ binwalk ~/Downloads/Image 
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
5599232       0x557000        ELF, 64-bit LSB shared object, version 1 (SYSV)
5726144       0x575FC0        CRC32 polynomial table, little endian
6784903       0x678787        Unix path: /dev/vc/0
6887392       0x6917E0        xz compressed data
7027328       0x6B3A80        Unix path: /lib/firmware/updates/5.6.0
7130168       0x6CCC38 …
```
=> Add ARM64 Linux image signature

.dockerignore, .travis.yml, Dockerfile, deps.sh
Create Dockerfile for binwalk.
=> 525 publish binwalk as a docker image

NOTICE.md
This PR is to merge in a third party notice file into each repo
=> Add Third Party Notice

.gitattributes, README.md
=> Edit README.md to be neater and added .gitattributes

dependencies/README.md
=> dependencies/readme.md: Fix typo

.github/workflows/quality.yaml
This PR wants to add a github workflow triggered for each pull requests that check for:
- links correctness using [lychee](https://github.com/lycheeverse/lychee)
- code formatting using standard `cargo fmt`
=> github workflows: first quality check

.github/workflows/quality.yaml
This PR adds another workflow to `quality.yaml` to trigger clippy on pull requests
=> add github workflow lint check

src/extractors/common.rs
Fix #725.
I'm not really familiar with Rust, so correct me if there's anything wrong.
=> extractors/common: support Chroot path on windows

src/signatures/pem.rs
This PR adds some missing PEM signatures.
=> feat: Add more PEM signatures

src/magic.rs, src/signatures/aes.rs
Added a bunch of tables commonly found in embedded systems.
=> Add AES forward and reverse tables, RCON and acceleration

src/binwalk.rs
This removes the need for admin privileges with windows. This fixes #838
=> switch from symlink to hardlink

src/signatures/jffs2.rs
=> Bump up allowed page size in JFFS2 analysis
