ReFirmLabs/binwalk

- src/binwalk/magic/archives
The use of the conditional match for Zip file signatures prevents "binwalk -y archive input" from matching correctly.
> Move 'archive data' string for Zip to ensure match on binwalk -y archive

- src/binwalk/modules/disasm.py
currently binwalk is broken and refuses to do anything if python3 capstone bindings are installed as it tries to call 'iteritems' on a dictionary (which was removed in python3)
> binwalk --help
Traceback (most recent call last):
File "/usr/bin/binwalk", line 26, in <module>
import binwalk.modules
File "/usr/lib/python3.4/site-packages/binwalk/modules/__init__.py", line 3, in <module>
from binwalk.modules.disasm import Disasm
File "/usr/lib/python3.4/site-packages/binwalk/modules/disasm.py", line 16, in <module>
class Disasm(Module):
File "/usr/lib/python3.4/site-packages/binwalk/modules/disasm.py", line 50, in Disasm
description="ARM executable code, 32-bit, big endian"),
File "/usr/lib/python3.4/site-packages/binwalk/modules/disasm.py", line 13, in __init__
for (k, v) in …
> binwalk does not start if python3 capstone bindings are installed [fixing python3 --disas option (using compat dict iterator)]

- src/binwalk/magic/firmware
The signature for the TRX header is still incomplete for v1. According to http://wiki.openwrt.org/doc/techref/header, offset[0] = lzma-loader, offset[1] = Linux-Kernel and offset[2] = rootfs.
Before the fix:
bernardomr@splinter ~/openwrt $ binwalk openwrt-wrtsl54gs-squashfs.bin 
DECIMAL       HEXADECIMAL     DESCRIPTION
32            0x20            TRX firmware header, little endian, header size: 32 bytes, image size: 1323008 bytes, CRC32: 0x6CAC483, flags: 0x0, version: 1, kernel offset: 0x1C, rootfs offset: 0x8D8
60            0x3C            gzip compressed data, maximum compression, from Unix, NULL date:
2296          0x8F8           LZMA compressed data, properties: 0x6D, dictionary size: 8388608 bytes, uncompressed size: -1 bytes
517152        0x7E420         Squashfs filesystem, …
> Fixed TRX v1 signature bug

- src/binwalk/magic/firmware
Header from TRX v1 has 28 bytes while TRX v2 has 32 bytes.
> TRX Header Size Fix

- src/binwalk/config/extract.conf
Currently, with some firmware images, `sasquatch` will attempt to auto-detect firmware endianess, and fail because the heuristic is not always correct. Instead, modify `binwalk` to explicitly attempt both byte-orderings with `sasquatch`.
> explicitly attempt both byte-orderings with sasquatch

- src/binwalk/config/extract.conf
the arguments to sasquatch were being passed in wrong order, which broke extraction. the endianness flag should come before the `-d <pathname>` argument.
> fix previous commit that modified sasquatch arguments (ab2ace76dd3521c39394e4f3daf8dfbfe2d464d3)

- src/binwalk/magic/firmware
Unfortunately, QNAP encrypted firmware can be identified only by a footer (and not a header), but there is no easy way in binwalk (that I could find) to check a negative-offset signature before positive-offset signatures. So this signature is suboptimal, because it will only trigger after searching through the entire file.
> add signature for encrypted qnap firmware

- src/binwalk/core/display.py
- src/binwalk/core/magic.py
- src/binwalk/modules/extractor.py
In Python 3.4, if the interpreter is launched with e.g. LANG=C environment,
binwalk fails with UnicodeDecodeError, since it tries to decode included
magic files (such as src/binwalk/magic/linux) with ascii codec. This patch
makes sure that utf-8 codec is always used.
> Make sure binwalk always opens files with utf-8 encoding

- src/binwalk/config/extract.conf
- src/binwalk/plugins/lzmaextract.py
use internal lzmaextract for xz and 7z as an alternative (tar can only handle tar.xz archives).
Example: http://downloads.linksys.com/downloads/firmware/1224703410530/FW_RE4100W_v1.0.00.008_20141009.bin
> use internal lzmaextract for xz and 7z as an alternative

- deps.sh
deps.sh was missing a sudo. Looks like setup.py drops some files as root.
> missing SUDO

- deps.sh
I found the problem with the apt dependencies not being installed - one character out of place!
I've also added `set -o nounset` to help prevent further bugs like this.
> Fix typo preventing apt dependency install

- deps.sh
Certain Debian-based distribution like Kali Linux 2016.1 don't include `cramfsprogs` in the package repository. This causes `deps.sh` to fail when installing packages, but since this return value isn't checked, the errors will propagate and `sasquatch` will fail to compile, for example, if the system is also missing `zlib1g-dev`. Checking the return value of the package installation command fixes this, though more generally `set -o errexit` also works. Unfortunately, passing the `-m` parameter to `apt-get` for `--ignore-missing` doesn't work, because packages with no installation candidate produce an invalid command, instead of missing packages.
> deps: check for package installation failure

- src/binwalk/modules/extractor.py
Fixes regression since 5fdad3c5ffe63efc1f0b213a56dd962477f7190f which ignored the -C option and wrote all files in the current working directory.
Tested with:
touch foo && gzip foo && mkdir bar
binwalk -e foo.gz -C bar
binwalk -e foo.gz
> Fix custom output directory for extracted files

- src/binwalk/core/settings.py
I was a bit surprised to get an "UnicodeDecodeError: 'utf-8' codec can't
decode byte 0xbe in position 21: invalid start byte" error while
writing and testing a new magic file.
It turns out that binwalk tried to parse the Vim swap file (.magic.swp)
as a magic file which obviously fails. Therefore ignore all files not
starting with an alphanumeric character.
___
The check could be made even stronger such that files like `magic.orig`, `magic.dpkg-old` or `magic.pacnew` are ignored, but this is already a good start I guess. Maybe the plugin path discovery needs a similar fix?
> Ignore dotfiles when discovering magic files

- src/binwalk/core/module.py
Fixes #207 , also the Signature module was "leaking" memory.
The `Signature` module `magic_files` attribute is initialized via kwarg.  When no `magic_files` argument is specified (the default mode), it receives a reference to the default empty list. During Signature's init() method, this list is modified, and because it is modifying the class variable default, it continues to grow every time the Signature module executes. This causes a long-running binwalk process to appear to leak memory and the duplicate signatures cause each subsequent iteration of `binwalk.scan` to run slower.
```
import binwalk
import binwalk.modules
from binwalk.modules import Signature
from binwalk.core.module import Modules
magic_files = [k for k in binwalk.modules.Signature.KWARGS if k.name=="magic_files"][0]
m = …
```
> Update kwarg processing to ensure modules don't receive a mutable reference to defaults

- src/binwalk/magic/animation
As you suggested in issue 225, multiple magic bytes makes detection of these MPEG transport streams work.
> adding MPEG transport stream signatures to magic/animations

- src/binwalk/magic/archives
See: https://users.cs.jmu.edu/buchhofp/forensics/formats/pkzip.html
The previous zip footer signature only displayed comment length without the added footer (End of central directory record.) This was potentially confusing when trying to dd out an archive.
> Zip footer signature accurately reflects its size

- src/binwalk/magic/archives
refs:
https://en.wikipedia.org/wiki/Tar_(computing)
https://www.gnu.org/software/tar/manual/html_node/Standard.html (see TVERSION)
The combination of a weak TAR signature and the tar.py plugin can lead to instances where a false-positive result has a "jump" value. This jump value could render further true-positive signatures invalid. This is particularly noticeable in firmware images that contain TAR parsers that do a string match on "ustar" themselves.
> Strengthening TAR signature.

- src/binwalk/magic/misc
See http://www.xilinx.com/support/answers/7891.html
Xilinx FPGA bitstreams start with one or more dummy words (0xffffffff) and a sync word (0xaa995566). Tested on files for several Spartan targets.
> Xilinx FPGA bitstream

- src/binwalk/modules/compression.py
Hi, I think there's a bug here.
Per the [BlockFile docstring](/devttys0/binwalk/blob/master/src/binwalk/core/common.py#L256), `read_block()` can return **more** than `dlen` bytes of data, by peeking, and this is intended feature.
However, we don't want the peek'd extra bytes injected into the stream being decompressed -- as the next `read_block()` call will pull them again!
Take a ~1.5 MiB deflated file to test: `binwalk -X` will extract a slighly larger file than a plain `zlib.decompress(-15)` would. (This, exactly, was how this bug bite me.)
Hope this fix is simple enough to be merged easily! Cheers.
> Fix extra data mistakingly "extracted" from raw Deflate streams

- src/binwalk/core/module.py
Currently, if you try calling 
`import binwalk
for module in binwalk.scan('f1.bin', signature=True, quiet=True):
print("DONE")
`
then whether or not you pass [True, False, or None] to quiet (or any other binary flag, for that matter), it will take whatever the default Kwarg value is, because it only appends the kwarg name, not the value. This only appends the kwarg if it is set to True (as all kwargs default to False), so that it can actually be toggled programmatically from python.
The change to argv/kargv to 'None' was just a minor cleanup to avoid unsafe behavior; lists/dicts as default values will persist any values added to them across function calls.
> Added ability to toggle binary flags through python kwargs

- src/binwalk/magic/crypto
This change limits the size of extracted DER sequences to the size given in the sequence's length field.
> Limit extracted size of DER sequence data

- deps.sh
2.Seperate dependencies now used for ubuntu 17
- cramfsprogs is not in default repos for 17
> 1.deps.sh now checks distro version number and displays it

- src/binwalk/modules/extractor.py
This pull request adds support for extracting into subdirectories named by the offset, so for example:
```
23372         0x5B4C          LZMA compressed data, properties: 0x5D, dictionary size: 33554432 bytes, uncompressed size: 121636 bytes
```
Will be extracted into a subdirectory named `0x5B4C`. I find this quite useful for getting a better overview into the extraction directory.
> Add support for extracing into subdirectories named by the offset.

- src/scripts/binida.py
Starting with IDA 7.0, the use of the Actions API is mandatory.
This enables Binwalk IDA plugin support for users of IDA versions 7.0+ without any compatibility changes for users of versions >= 3.95
This closes issue [#319 ](https://github.com/ReFirmLabs/binwalk/issues/319)
> Support for IDA versions >= 7.0

- src/binwalk/magic/firmware
More modern Ubiquiti devices use signed firmware with a different end header.
This PR adds support for the new signed end headers.
The new header start with the string "ENDS" which is followed by a 2048 bit
RSA sha1 signature.
> Add magic for signed Ubiquiti end headers

- src/binwalk/magic/firmware
The zero-padding used to identify the PART and END headers is not part of the header itself but rather padding from previous data structures.
Also offsets were wrong, resulting in wrong base addresses and partition sizes.
Before:
After:
> Fix Ubiquiti partiton PART and END headers

- src/binwalk/magic/firmware
This commit adds support for automated discovery of flattened device trees which are very common in embedded device firmware.
Before binwalk was unable to identify device trees:
```
[tsys@sunsetshimmer cortexa9]$ binwalk zImage_dtb 
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
36            0x24            Linux kernel ARM boot executable zImage (little-endian), load address: "0x00000000", end address: "0x003C7C38"
18148         0x46E4          gzip compressed data, maximum compression, from Unix, NULL date (1970-01-01 00:00:00)
```
With this commit applied binwalk identifies devicetrees correctly:
```
[tsys@sunsetshimmer cortexa9]$ binwalk zImage_dtb 
DECIMAL       HEXADECIMAL     DESCRIPTION …
```
> Add signature of flattened device trees

- src/binwalk/core/settings.py
When running binwalk in non-interactive session some environment variables may not be set. This causes binwalk to fail to correctly determine user's home directory. This commit fixes that (at least for linux systems).
It should be also tested on Windows systems.
> fix getting user's home dir

- src/binwalk/core/module.py
`next_target_file` being Unicode got past the `str` check and threw an error at `self.status.total = fp.length`.
> Fixed issue with next_target_file being unicode and causing an exception

- API.md
The example code in `API.md` doesn't work in python 3 because `has_key()` is deprecated. My commit replaces `has_key()` with `in`.
Alternatively, the API docs could suggest importing the binwalk compat module, as shown below:
```python
from binwalk.core.compat import *
```
> make API example python3 compliant

- src/binwalk/magic/firmware
Back in January I added a new signature for flattened device tree blobs (#381). Unfortunately there was already a signature that I did not notice.
Since my magic contains a lot more checks I would like to remove the old one.
> Remove conflicting signature for flattened device trees

- deps.sh
Version 1.1 of cramfs does not build anymore with glibc 2.28 because
since this version glibc no longer includes <sys/sysmacros.h> from
<sys/types.h>, and therefore <sys/sysmacros.h> must be included
explicitly when major()/minor() are used.
To fix this issue, use new upstream project which includes
https://github.com/npitre/cramfs-tools/commit/434aabd67a39165ee0750c0e0d25213bf2ec8fa5
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> deps.sh: use new upstream cramfs-tools

- src/binwalk/magic/crypto
- src/binwalk/plugins/pgp.py
This should detect pgp signatures such as those in #256. This signature detection is adapted from the [file pgp signature](https://github.com/file/file/blob/FILE5_37/magic/Magdir/pgp#L122-L210).
I also have automatic pgp decryption working as well when a known key is detected.
> Add signature/decryption support for PGP RSA encrypted session key

- .travis.yml
Python 3.3 is no longer supported, so remove it from the CI matrix to make builds green again.
> Stop testing on unsupported Python 3.3

- .travis.yml
Drop Python 3.3 which isn't available anymore, add python 3.7 and 3.8 instead.
> travis: Update Python versions

- src/binwalk/modules/extractor.py
Make it clear that ext/cmd are optional and that the type can be a regular
expression.
> Improve help output for --dd

- src/binwalk/magic/filesystems
Newest squashfs in upstream has supported LZ4 (5) and ZSTD (6) as compression algorithms. However, they didn't exist in binwalk's current magic library. This commit added the magic values so that squashfs images compressed by these algorithms could be successfully identified.
Ref:
[https://github.com/torvalds/linux/blob/master/fs/squashfs/squashfs_fs.h](https://github.com/torvalds/linux/blob/master/fs/squashfs/squashfs_fs.h) (see `LZ4_COMPRESSION` and `ZSTD_COMPRESSION`)
[https://github.com/file/file/blob/master/magic/Magdir/filesystems](https://github.com/file/file/blob/master/magic/Magdir/filesystems) (see `lz4` and `zstd`) under Squashfs. 
Have tested this modification with some real world firmware images I met.
> Added lz4 and zstd comporessions to squashfs.

- src/binwalk/config/extract.conf
when extract firmware with two same filesytem type , they will be mount at same directory and cause error. So we need add UNIQUE_PATH_DELIMITER to mount point.
> add UNIQUE_PATH_DELIMITER to mount command

- src/binwalk/magic/firmware
Ubiquiti firmware images have additional data attached after the Ubiquiti
partition definitions. They are used to convey additional pre-upgrade
information and even firmware signatures (AirOS 6).
Output before commit:
```
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             Ubiquiti firmware header, header size: 264 bytes, ~CRC32: 0x84031317, version: "XM.ar7240.v6.0.4-sign.31631.170908.1605"
268           0x10C           Ubiquiti partition header, header size: 56 bytes, name: "PARTu-boot", base address: 0x9F000000, data size: 219336 bytes
140596        0x22534         U-Boot version string, "U-Boot 1.1.4.2-s1031 (May  4 2017 - 15:26:57)"
140788        0x225F4         CRC32 polynomial …
```
> Add signature for Ubiquiti firmware additional data

- src/binwalk/modules/entropy.py
The entropy graph can be severely broken when used together with the `--signature` option (e.g. `binwalk -BEJ`).
In cases where many signatures hit, the legend can cover the whole plot:
This fix moves the legend to the right of the plot. This should ensure there is no overlap:
> moved entropy legend

- src/binwalk/magic/firmware
This is used by Zyxel for the firmware in their GS1900 series switches,
but also shows up in Cisco 220 series.
It's really just the U-Boot header with a different initial magic value.
Also minor cleanup in the U-Boot signature.
> Add signature for bix firmware file format

- src/binwalk/modules/entropy.py
Improved speed of entropy scan by using a list rather than a dictionary for seen values
Optional: vastly improved speed with numpy/numba implementation
The implementation detects whether numpy/numba are installed and automatically leverages them.
The speed improvements are fairly substantial. I generated a 2GB file of random data to benchmark the different implementations. Tests performed on an i5-6500 (dual core/ four thread) with an HDD and measured with `time binwalk -E -N <file>`
| Implementation             | Time (real) |  Time (user) | Time (sys) |
|----------------------------|--------------|-------|--------|
| Original Binwalk           | 3m16.936     | 3m8.363     | 0m1.252     |
| Improved Implementation    | 2m32.586     | 2m23.660    | 0m1.182     |
| Numpy Implementation …
> Improves speed of entropy scan

- src/binwalk/magic/firmware
This PR adds support for Autel EVO I/II firmware magic detection. Currently this only adds the magic detection piece and not extraction.
Sample firmware files can be found on the bottom of Autel's download website.
EVO I: https://auteldrones.com/pages/evo-downloads
EVO II: https://auteldrones.com/pages/evo-ii-downloads
> Autel EVO firmware magic support

- src/binwalk/core/magic.py
These operators are listed in the "Signature File Format" wiki page but don't actually exist.  Fixes issue #485.
> Actually implement exponent and shift operators

- src/binwalk/config/extract.conf
Call 'unzip' with empty password, to avoid 'unzip' stuck in interactive mode when process encrypt files
> Fix: binwalk stuck when extract encrypt zip files

- README.md
https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default
Several other distros as well.
> Ubuntu Focal is Python 3 by default

- INSTALL.md
- deps.sh
- src/binwalk/config/extract.conf
Removing support for stuffit archives as they are generally no longer needed.
> Remove unstuff from dependencies

- src/binwalk/plugins/unpfs.py
`os.path.join` does not fully resolve a path so the condition that follows will never be true. Fixed by resolving the path using `os.path.abspath`.
An attacker could craft a malicious PFS file that would cause binwalk to write outside the extraction directory. I attached a proof-of-concept ([poc.zip](https://github.com/ReFirmLabs/binwalk/files/9873311/poc.zip)) that, when extracted from the user's home directory, would extract a malicious binwalk module in `.config/binwalk/plugins`. This malicious plugin would then be loaded and executed by binwalk, leading to RCE.
---
PoC run:
```
/usr/local/bin/binwalk -M -e /tmp/poc.zip
Scan Time:     2022-10-26 21:50:26
Target File:   /tmp/poc.zip
MD5 Checksum:  4fdad30c7c1b4915938b5ad2786f5bf8
Signatures:    411
DECIMAL       HEXADECIMAL …
```
> fix path traversal in PFS extractor script

- src/binwalk.rs
- src/extractors/common.rs
Quick PR to add a few changes to allow windows to compile binwalk, being; symlinking and file permissions
> Add support for windows compilation

- src/main.rs
This PR wants to make changes to improve the main loop.
Currently the main loop is using a `VecDeque` to schedule jobs on the threadpool, but the threadpool implements an internal queue itself, so basically there the code is redundant.
You can test this `Threadpool` behaviour with these simple lines:
```rust
fn main() {
let pool = threadpool::ThreadPool::new(3);
for x in 0..6 {
pool.execute(move || {
println!("start work {x}");
std::thread::sleep(std::time::Duration::from_secs(3));
println!("end work {x}");
});
}
pool.join();
}
```
There is also a manual `thread::sleep` that can be avoided, relying on the `Receiver::recv` function and without actively checking for results in the channel receiver.
I think in general the main loop will be less convoluted.
> main loop refactor: remove redundant queue and no active waiting for results

- Dockerfile
added gcc as a dependency install so it would build the image propperly.
fixing my own issue. Add gcc to Dockerfile in binwalkv3 #692
> Update Dockerfile build dependency install gcc

- src/magic.rs
- src/signatures.rs
- src/signatures/luks.rs
- src/structures.rs
- src/structures/luks.rs
This PR adds basic support for detecting LUKS headers:
https://en.wikipedia.org/wiki/Linux_Unified_Key_Setup
Currently I'm only parsing the version and the hash function because those are the two fields that are in the same offsets in versions 1 and 2 of LUKS.
After that version 1 and 2 start to diverge, and will take some more work to parse them separately.
Test data was generated as follows:
```
dd if=/dev/zero of=test1.bin count=100000 bs=1024
dd if=/dev/zero of=test2.bin count=100000 bs=1024
cryptsetup luksFormat --type luks1 test1.bin
cryptsetup luksFormat --type luks2 test2.bin
echo -e "LUKS\xba\xbe\x00\xff" > test3.bin # FALSE POSITIVE TEST (invalid version number)
```
Output for LUKS vesion 1:
```
/home/nmatt/work/research/binwalkv3/testfw/test1.bin …
```
> add basic LUKS header support

- fuzzing/Cargo.lock
- src/binwalk.rs
- src/extractors/common.rs
- src/main.rs
- src/signatures/gif.rs
- src/signatures/jpeg.rs
- src/signatures/lzfse.rs
- src/signatures/png.rs
- src/signatures/svg.rs
Fixes excessive memory & disk consumption issues:
1. Massive memory consumption in ThreadPool during recursive extraction on large images
2. Unnecessary `to_vec()` calls
3. Unnecessary file carving on some file types
4. Additional useful debug output
Also fixes a bug in LZFSE parser loop.
> Mem cleanup

- src/magic.rs
- src/signatures/lzma.rs
- src/signatures/tplink.rs
- src/structures/tplink.rs
Added  signature for TPLink RTOS firmware.
Fixed how uncompressed LZMA size is displayed.
> Tplink fw rtos sig

- dependencies/src.sh
- src/binwalk.rs
- src/extractors.rs
- src/extractors/apfs.rs
- src/magic.rs
- src/signatures.rs
- src/signatures/apfs.rs
- src/structures.rs
- src/structures/apfs.rs
> Apfs support

- src/binwalk.rs
- src/cliparser.rs
- src/extractors/zlib.rs
- src/main.rs
- src/signatures/compressd.rs
- src/signatures/fat.rs
- src/signatures/gpg.rs
- src/signatures/zlib.rs
> Full search

- src/extractors.rs
- src/extractors/dahua_zip.rs
- src/extractors/gif.rs
- src/magic.rs
- src/signatures.rs
- src/signatures/dahua_zip.rs
- src/signatures/zip.rs
https://ipcamtalk.com/threads/dahua-dhi-asi7213x-t1-firmware-analysis.57773/
> Added support for Dahua ZIP archives

- src/extractors/sevenzip.rs
The latest 7zip version supports unix systems, so it can be used instead of the old unix port (last version of p7zip is from 2016, see https://sourceforge.net/projects/p7zip/). 
Related with this I have a small question. How to have multiple extractors for the same signature? I have seen in display.rs that it supports multiple extractors, but I didn't see an argument for the signature types in the Extractor type.
> switch from p7zip to 7zip

- src/extractors/squashfs.rs
- src/signatures/squashfs.rs
The `sasquatch` utility sometimes does not correctly detect the endianness of a SquashFS image.
Explicitly specify the endianness when executing `sasquatch`.
> Explicitly pass endianness to sasquatch

- src/binwalk.rs
- src/cliparser.rs
- src/main.rs
Adds `--carve` command line option which carves known and unknown data blocks from a file to disk during extraction.
> Carve file data to disk

- src/extractors.rs
- src/extractors/dlink_tlv.rs
- src/magic.rs
- src/signatures/dlink_tlv.rs
Added dlink_tlv file carver; updated signature to report encrypted firmware
> D-Link TLV file carver

- src/binwalk.rs
- src/main.rs
- Added a BinwalkError struct with a message field to store error messages.
- Stored error messages during binwalk initialization.
- Display error message when binwalk initialization fails.
Very minor changes, I was just getting some initialization errors when implementing the API in my own project. When binwalk failed to initialise I was catching the BinwalkError but it did not provide any indication as to what went wrong.
> Minor changes to binwalk error handling

- src/signatures/xz.rs
- src/structures/xz.rs
> Improved XZ signaturing, added support for malformed XZ streams

- src/structures/riff.rs
Fixes #810
I noticed the chunk type was not being read correctly so that is also fixed
> Fixed riff signature for files other than webp and fix chunk type

- src/cliparser.rs
- src/main.rs
> Fixed output when no command line options are specified

- Cargo.lock
- Cargo.toml
- fuzzing/Cargo.lock
- fuzzing/Cargo.toml
- src/extractors/lzma.rs
1. Migrate from unmaintained `xz2` crate to maintained `liblzma`.
2. Update `bzip2`, which now by default enables `libbz2-rs-sys` ([1](https://github.com/trifectatechfoundation/bzip2-rs/releases/tag/v0.6.0)).
3. Update other dependencies of main project and fuzzing.
> Update rust deps
